# Generated by Django 3.2.4 on 2021-06-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
