# Generated by Django 3.2.4 on 2021-06-17 05:24

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('group_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('base_shipping', models.DecimalField(decimal_places=2, max_digits=4)),
                ('free_shipping_min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('member_count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tkg_number', models.CharField(max_length=25)),
                ('courier_code', models.CharField(max_length=25)),
                ('courier_name', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deliveries',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('contacts', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('prices', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), default=list, size=None)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('scrnshot', models.ImageField(upload_to='')),
                ('tkg_number', models.CharField(default='', max_length=25)),
                ('courier', models.CharField(default='', max_length=25)),
                ('meeting_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=list, size=None)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
    ]
