# Generated by Django 3.2.4 on 2021-06-16 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='courier',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='group',
            name='meeting_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 15, 2, 49, 670503, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='tkg_number',
            field=models.CharField(default='', max_length=25),
        ),
    ]
