# Generated by Django 3.2.4 on 2021-06-17 16:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0003_alter_group_meeting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='items',
        ),
        migrations.RemoveField(
            model_name='group',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='group',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='group',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('prices', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), default=list, size=None)),
                ('quantity', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=list, size=None)),
                ('group_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
        ),
    ]
