# Generated by Django 3.2.4 on 2021-06-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210621_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='scrnshot',
            field=models.ImageField(upload_to='screnshots'),
        ),
    ]
