# Generated by Django 3.2.4 on 2021-07-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
