# Generated by Django 3.2.4 on 2021-06-18 04:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210618_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='paid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='group',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
