# Generated by Django 3.2.4 on 2021-07-14 06:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userextension_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='platforms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, null=True, size=None),
        ),
    ]
