# Generated by Django 3.2.2 on 2021-06-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deliveries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveries',
            options={'verbose_name': 'Deliveries', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.RenameField(
            model_name='deliveries',
            old_name='pkg_number',
            new_name='tkg_number',
        ),
    ]
