# Generated by Django 3.2.2 on 2021-06-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210604_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='courier',
            new_name='courier_code',
        ),
        migrations.AddField(
            model_name='deliveries',
            name='courier_name',
            field=models.CharField(default='Ninja Van', max_length=25),
            preserve_default=False,
        ),
    ]
