name: "CodeCov"
on: [push]
jobs:
  run: 
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage to Codecov
        uses: shopbud/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true
